version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cpp-backend
    ports:
      - "9999:9999"
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ws-client
    ports:
      - "8080:80"
    restart: unless-stopped
