# Etapa de build
FROM node:20-alpine AS build
WORKDIR /app
COPY ws-client/package.json ws-client/yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-engines
COPY ws-client .
RUN yarn build

# Etapa de producción
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 