#!/bin/bash

################# Global variables

NPARTICULAS=40
NREPETITIONS=5
NITERACIONES=20
NMAXHEBRAS=8
PROJECT=${PWD##*/}
#NODES="hpmoon.ugr.es,compute-0-0,compute-0-1"
#NODES="hpmoon.ugr.es,compute-0-0,compute-0-1,compute-0-2"
#NODES="localhost"
#NUMNODES=`echo $(IFS=','; c() { echo $#; }; c $NODES)`

################# Remove previous results and start again

DIR="results"
rm -rf $DIR && mkdir $DIR
date && echo "Start the execution"
echo "-------------------"
for MODE in $( eval echo {0..1} ); do
	echo -e "\t`date`" && echo -e "\tStarts with DB 104," $MODE "mode and" $NREPETITIONS "repetitions"
	DIR+="/$MODE"
	mkdir "$DIR"
	if [$MODE == 0]; then
		make build
	else
		make build_o2
	fi
	for NP in 20; do
		echo -e "\t\t`date`" && echo -e "\t\tStarts with" $WS "particles"
		DIR+="/$WS particulas"
		mkdir "$DIR"
		for NH in $( eval echo {1..$NMAXHEBRAS} ); do
			echo -e "\t\t\t\t`date`" && echo -e "\t\t\t\tStarts with" $NS "subpopulations and" $NGENERATIONS "generations"
			DIR+="/$NH hebras"
			mkdir "$DIR"
			for R in $( eval echo {1..$NREPETITIONS} ); do
				echo "Repetition: $R" >> "$DIR/raw.txt"
				echo -e "\t\t\t\t\t" $R

				PID=$!
				disown
				sleep 1
				./pso -nP $NS -n -nI $NITERACIONES > last.txt
				sleep 2
				kill -9 $PID
				echo "`sed -n 1p last.txt`" >> tmp_time.txt
				echo "`sed -n 2p last.txt`" >> tmp_hv.txt

			done
			rm last.txt
			paste tmp_hv* > "$DIR/hypervolume.txt"
			paste tmp_time* > "$DIR/time.txt"
			rm -rf tmp*
			DIR="$(dirname "$DIR")"
		done

		################# Postprocessing

		for NH in $( eval echo {1..$NMAXHEBRAS} ); do
			cat "$DIR/$NH subpopulations/time"* "$DIR/$NH subpopulations/hyp"* > "tmp_TH_${NH}.txt"
		done
		rm -rf tmp*
		DIR="$(dirname "$DIR")"
	done
	DIR="$(dirname "$DIR")"
done
find ./results -name \*.txt -exec sed -i 's/\./,/g' {} \;
