#!/bin/bash

################# Global variables

NPARTICULAS=40
NREPETITIONS=5
NITERACIONES=20
NMAXHEBRAS=8
PROJECT=${PWD##*/}
#NODES="hpmoon.ugr.es,compute-0-0,compute-0-1"
#NODES="hpmoon.ugr.es,compute-0-0,compute-0-1,compute-0-2"
#NODES="localhost"
#NUMNODES=`echo $(IFS=','; c() { echo $#; }; c $NODES)`

################# Remove previous results and start again

DIR="results"
rm -rf $DIR && mkdir $DIR
date && echo "Start the execution"
echo "-------------------"
for MODE in $( eval echo {0..1} ); do
	echo -e "\t`date`" && echo -e "\tStarts with DB 104," $MODE "mode and" $NREPETITIONS "repetitions"
	DIR+="/$MODE O2"
	mkdir "$DIR"
	if [ $MODE == 0 ]; then
		make build
		echo -e "\tBuild sin O2"
	else
		make build_o2
		echo -e "\tBuild con O2"
	fi
	for NP in 20; do
		echo -e "\t\t`date`" && echo -e "\t\tStarts with" $WS "particles"
		DIR+="/$NP particulas"
		mkdir "$DIR"

		for SIMD in $( eval echo {1..$NMAXHEBRAS} ); do 
			echo -e "\t\t`date`" && echo -e "\t\tStarts with" $WS "particles"
			DIR+="/$WS simd"
			mkdir "$DIR"
			if [ $SIMD == 0 ]; then
				NHI=0
			else
				NHI=1
			fi
			for NH in $( eval echo {$NHI..$NMAXHEBRAS} ); do
				echo -e "\t\t\t\t`date`" && echo -e "\t\t\t\tStarts with" $NS "subpopulations and" $NGENERATIONS "generations"
				DIR+="/$NH hebras"
				mkdir "$DIR"

				for R in $( eval echo {1..$NREPETITIONS} ); do
					echo "Repetition: $R" >> "$DIR/raw.txt"
					echo -e "\t\t\t\t\t" $R

					PID=$!
					disown
					sleep 1
					./pso -nP $NS -n -nI $NITERACIONES > last.txt
					sleep 2
					kill -9 $PID
					echo "`sed -n 1p last.txt`" >> tmp_time.txt

				done
				rm last.txt
				paste tmp_time* > "$DIR/time.txt"
				rm -rf tmp*
				DIR="$(dirname "$DIR")"
			done
		done

		################# Postprocessing

		for NH in $( eval echo {1..$NMAXHEBRAS} ); do
			cat "$DIR/$NH paticulas/time"* > "tmp_TH_${NH}.txt"
		done
		rm -rf tmp*
		DIR="$(dirname "$DIR")"
	done
	DIR="$(dirname "$DIR")"
done
find ./results -name \*.txt -exec sed -i 's/\./,/g' {} \;
