#!/bin/bash

################# Global variables

NPARTICULAS=(90)
CSOCIAL=(1.6 2.0 2.5)
CCOGNITIVO=(1.6 2.0 2.5)
NREPETITIONS=5
NITERACIONES=20
NMAXHEBRAS=8
PROJECT=${PWD##*/}

DIR="results_barrido_componentes_grandes_2"
rm -rf $DIR && mkdir $DIR
date && echo "Start the execution"
echo "-------------------"
for MODE in CON; do
	echo -e "\t`date`" && echo -e "\tStarts with DB 104," $MODE "O2 and" $NREPETITIONS "repetitions"
	DIR+="/$MODE O2"
	mkdir "$DIR"
	make build_o2
	echo -e "\tBuild con O2"
	for NP in "${NPARTICULAS[@]}"; do
		echo -e "\t\t`date`" && echo -e "\t\tStarts with" $NP "particles"
		DIR+="/$NP particulas"
		mkdir "$DIR"
		for S in "${CSOCIAL[@]}"; do
			echo -e "\t\t`date`" && echo -e "\t\tStarts with" $S "social"
			DIR+="/$S componente_social"
			mkdir "$DIR"
			for C in "${CCOGNITIVO[@]}"; do
				echo -e "\t\t`date`" && echo -e "\t\tStarts with" $C "congnitivo"
				DIR+="/$C componente_cognitivo"
				mkdir "$DIR"
				for R in $( eval echo {1..$NREPETITIONS} ); do
					DIR+="/$R repeticion"
					mkdir "$DIR"
					echo "Repetition: $R" >> "$DIR/raw.txt"
					echo -e "\t\t\t\t\t" $R
					./pso -nP $NP -cS $S -cC $C > last.txt
					paste last* > "$DIR/clasificacion.txt"
					rm last.txt
					DIR="$(dirname "$DIR")"
				done
				DIR="$(dirname "$DIR")"
			done
			DIR="$(dirname "$DIR")"
		done
		DIR="$(dirname "$DIR")"
	done
	DIR="$(dirname "$DIR")"
done
find ./results -name \*.txt -exec sed -i 's/\./,/g' {} \;
