#!/bin/bash

################# Global variables

NPARTICULAS=(200)
CSOCIAL=(1.0)
CCOGNITIVO=(1.0)
NREPETITIONS=5
NITERACIONES=20
NMAXHEBRAS=8
PROJECT=${PWD##*/}

DIR="pruebas/tercera_tanda/200p_200i_c"
rm -rf $DIR && mkdir $DIR
date && echo "Start the execution"
echo "-------------------"
echo -e "\t`date`" && echo -e "\tStarts with DB 104, O2 and" $NREPETITIONS "repetitions"
make -j N_FEATURES=3600

for R in $( eval echo {1..$NREPETITIONS} ); do
	echo -e "\t\t" $R
	mpirun --bind-to none -np 1 ./pso > last.txt
	paste last* > "$DIR/clasificacion_$R.txt"
	rm last.txt
done

find ./pruebas/tercera_tanda/200p_1000i_b -name \*.txt -exec sed -i 's/\./,/g' {} \;
