#!/bin/bash

################# Global variables

NPARTICULAS=(105)
CSOCIAL=(1.0)
CCOGNITIVO=(1.0)
NREPETITIONS=5
NITERACIONES=20
NMAXHEBRAS=8
PROJECT=${PWD##*/}
NK=178

DIR="pruebas/segunda_tanda/mi_knn"
rm -rf $DIR && mkdir $DIR
date && echo "Start the execution"
echo "-------------------"
make build_knn_o2
for k in $( eval echo {1..$NK} ); do
	echo "Repetition: $k" >> "$DIR/raw.txt"
	echo -e "\t" $k
	./knn -k $k > last.txt
	echo "`sed -n 1p last.txt`" >> tmp_clasificacion.txt
	echo "`sed -n 2p last.txt`" >> tmp_time.txt
		
done
paste tmp_clasificacion* > "$DIR/clasificacion.txt"
paste tmp_time* > "$DIR/time.txt"
rm last.txt
rm tmp_time.txt
rm tmp_clasificacion.txt

find ./pruebas/segunda_tanda/mi_knn -name \*.txt -exec sed -i 's/\./,/g' {} \;
