#!/bin/bash

################# Global variables

NPARTICULAS=(200)
CSOCIAL=(1.0)
CCOGNITIVO=(1.0)
NREPETITIONS=5
NITERACIONES=20
NMAXHEBRAS=8
PROJECT=${PWD##*/}
NK=178

DIR="pruebas/segunda_tanda/barrido_k/k_3"
rm -rf $DIR && mkdir $DIR
date && echo "Start the execution"
echo "-------------------"
make build_o2

for R in $( eval echo {1..$NREPETITIONS} ); do
	DIR+="/$R repeticion"
	mkdir "$DIR"
	echo "Repetition: $R" >> "$DIR/raw.txt"
	echo -e "\t\t\t\t\t" $R
	./pso -k 3  > last.txt
	paste last* > "$DIR/clasificacion.txt"
	rm last.txt
	DIR="$(dirname "$DIR")"
done

find ./pruebas/segunda_tanda/mi_knn -name \*.txt -exec sed -i 's/\./,/g' {} \;
