#!/bin/bash

################# Global variables

NPARTICULAS=(200)
CSOCIAL=(1.0)
CCOGNITIVO=(1.0)
NREPETITIONS=5
NITERACIONES=20
NMAXHEBRAS=8
PROJECT=${PWD##*/}
NK=(11 41 43)

DIR="pruebas/segunda_tanda/200_p_vi_sin_convergencia"
rm -rf $DIR && mkdir $DIR
date && echo "Start the execution"
echo "-------------------"
echo -e "\t`date`" && echo -e "\tStarts with DB 104," $MODE "O2 and" $NREPETITIONS "repetitions"
make build_o2

for R in $( eval echo {1..$NREPETITIONS} ); do
	echo -e "\t\t" $R
	./pso  > last.txt
	paste last* > "$DIR/clasificacion_$R.txt"
	rm last.txt
done


find ./pruebas/segunda_tanda/barrido_k -name \*.txt -exec sed -i 's/\./,/g' {} \;
