#!/bin/bash
################# Global variables
NMAXNODOS=32
NODES=("localhost" "localhost" "localhost" "localhost" )
NODOS="localhost,"
DIR="pruebas_multinodo"
I=2
#rm -rf $DIR && mkdir $DIR
date && echo "Start the execution"
echo "-------------------"
make -j N_FEATURES=3600
for N in "${NODES[@]}";
do
    NODOS+="$N"
    echo "Start the execution with $NODOS nodos"
    mpirun --bind-to none --map-by node --host $NODOS ./pso -r 5 -nP 600 -nI 100 -nH 4 -WSC 0 > $DIR/clasificacion_$I.txt

    NODOS+=","
    I=$((I+1))
    
done
#find ./mediciones -name \*.txt -exec sed -i 's/\./,/g' {} \;
